
import { MaritalStatus } from './types';

export const PTKP_RATES: { [key in MaritalStatus]: number } = {
    [MaritalStatus.TK0]: 54000000,
    [MaritalStatus.TK1]: 58500000,
    [MaritalStatus.TK2]: 63000000,
    [MaritalStatus.TK3]: 67500000,
    [MaritalStatus.K0]: 58500000,
    [MaritalStatus.K1]: 63000000,
    [MaritalStatus.K2]: 67500000,
    [MaritalStatus.K3]: 72000000,
};

export const PASAL_17_RATES = [
    { limit: 60000000, rate: 0.05 },
    { limit: 250000000, rate: 0.15 },
    { limit: 500000000, rate: 0.25 },
    { limit: 5000000000, rate: 0.30 },
    { limit: Infinity, rate: 0.35 },
];

export const TER_CATEGORY_MAP: { [key in MaritalStatus]: 'A' | 'B' | 'C' } = {
    [MaritalStatus.TK0]: 'A', [MaritalStatus.TK1]: 'A', [MaritalStatus.K0]: 'A',
    [MaritalStatus.TK2]: 'B', [MaritalStatus.TK3]: 'B', [MaritalStatus.K1]: 'B', [MaritalStatus.K2]: 'B',
    [MaritalStatus.K3]: 'C',
};

// Official TER Rates from PMK 168/2023
export const TER_RATES: { [key in 'A' | 'B' | 'C']: { limit: number, rate: number }[] } = {
    'A': [
        { limit: 5400000, rate: 0.00 },
        { limit: 5650000, rate: 0.0025 },
        { limit: 5950000, rate: 0.0050 },
        { limit: 6300000, rate: 0.0075 },
        { limit: 6750000, rate: 0.01 },
        { limit: 7500000, rate: 0.0125 },
        { limit: 8550000, rate: 0.0150 },
        { limit: 9650000, rate: 0.0175 },
        { limit: 10050000, rate: 0.02 },
        { limit: 10350000, rate: 0.0225 },
        { limit: 10700000, rate: 0.0250 },
        { limit: 11050000, rate: 0.03 },
        { limit: 11600000, rate: 0.0350 },
        { limit: 12500000, rate: 0.04 },
        { limit: 13750000, rate: 0.05 },
        { limit: 15100000, rate: 0.06 },
        { limit: 16950000, rate: 0.07 },
        { limit: 19750000, rate: 0.08 },
        { limit: 24150000, rate: 0.09 },
        { limit: 26450000, rate: 0.10 },
        { limit: 28000000, rate: 0.11 },
        { limit: 30050000, rate: 0.12 },
        { limit: 32400000, rate: 0.13 },
        { limit: 35400000, rate: 0.14 },
        { limit: 39100000, rate: 0.15 },
        { limit: 43850000, rate: 0.16 },
        { limit: 47800000, rate: 0.17 },
        { limit: 51400000, rate: 0.18 },
        { limit: 56300000, rate: 0.19 },
        { limit: 62200000, rate: 0.20 },
        { limit: 68600000, rate: 0.21 },
        { limit: 77500000, rate: 0.22 },
        { limit: 89000000, rate: 0.23 },
        { limit: 103000000, rate: 0.24 },
        { limit: 125000000, rate: 0.25 },
        { limit: 157000000, rate: 0.26 },
        { limit: 206000000, rate: 0.27 },
        { limit: 337000000, rate: 0.28 },
        { limit: 454000000, rate: 0.29 },
        { limit: 550000000, rate: 0.30 },
        { limit: 695000000, rate: 0.31 },
        { limit: 910000000, rate: 0.32 },
        { limit: 1400000000, rate: 0.33 },
        { limit: Infinity, rate: 0.34 }
    ],
    'B': [
        { limit: 6200000, rate: 0.00 },
        { limit: 6500000, rate: 0.0025 },
        { limit: 6850000, rate: 0.0050 },
        { limit: 7300000, rate: 0.0075 },
        { limit: 9200000, rate: 0.01 },
        { limit: 10750000, rate: 0.0150 },
        { limit: 11250000, rate: 0.02 },
        { limit: 11600000, rate: 0.0250 },
        { limit: 12600000, rate: 0.03 },
        { limit: 13600000, rate: 0.04 },
        { limit: 14950000, rate: 0.05 },
        { limit: 16400000, rate: 0.06 },
        { limit: 18450000, rate: 0.07 },
        { limit: 21850000, rate: 0.08 },
        { limit: 26000000, rate: 0.09 },
        { limit: 27700000, rate: 0.10 },
        { limit: 29350000, rate: 0.11 },
        { limit: 31450000, rate: 0.12 },
        { limit: 33950000, rate: 0.13 },
        { limit: 37100000, rate: 0.14 },
        { limit: 41100000, rate: 0.15 },
        { limit: 45800000, rate: 0.16 },
        { limit: 49500000, rate: 0.17 },
        { limit: 53800000, rate: 0.18 },
        { limit: 58500000, rate: 0.19 },
        { limit: 64000000, rate: 0.20 },
        { limit: 71000000, rate: 0.21 },
        { limit: 80000000, rate: 0.22 },
        { limit: 93000000, rate: 0.23 },
        { limit: 109000000, rate: 0.24 },
        { limit: 129000000, rate: 0.25 },
        { limit: 163000000, rate: 0.26 },
        { limit: 211000000, rate: 0.27 },
        { limit: 374000000, rate: 0.28 },
        { limit: 459000000, rate: 0.29 },
        { limit: 555000000, rate: 0.30 },
        { limit: 704000000, rate: 0.31 },
        { limit: 957000000, rate: 0.32 },
        { limit: 1405000000, rate: 0.33 },
        { limit: Infinity, rate: 0.34 }
    ],
    'C': [
        { limit: 6600000, rate: 0.00 },
        { limit: 6950000, rate: 0.0025 },
        { limit: 7350000, rate: 0.0050 },
        { limit: 7800000, rate: 0.0075 },
        { limit: 8850000, rate: 0.01 },
        { limit: 9800000, rate: 0.0125 },
        { limit: 10950000, rate: 0.0150 },
        { limit: 11200000, rate: 0.0175 },
        { limit: 12050000, rate: 0.02 },
        { limit: 12950000, rate: 0.03 },
        { limit: 14150000, rate: 0.04 },
        { limit: 15550000, rate: 0.05 },
        { limit: 17050000, rate: 0.06 },
        { limit: 19500000, rate: 0.07 },
        { limit: 22700000, rate: 0.08 },
        { limit: 26600000, rate: 0.09 },
        { limit: 28100000, rate: 0.10 },
        { limit: 30100000, rate: 0.11 },
        { limit: 32600000, rate: 0.12 },
        { limit: 35400000, rate: 0.13 },
        { limit: 38900000, rate: 0.14 },
        { limit: 43000000, rate: 0.15 },
        { limit: 47400000, rate: 0.16 },
        { limit: 51200000, rate: 0.17 },
        { limit: 55800000, rate: 0.18 },
        { limit: 60400000, rate: 0.19 },
        { limit: 66700000, rate: 0.20 },
        { limit: 74500000, rate: 0.21 },
        { limit: 83200000, rate: 0.22 },
        { limit: 95000000, rate: 0.23 },
        { limit: 110000000, rate: 0.24 },
        { limit: 134000000, rate: 0.25 },
        { limit: 169000000, rate: 0.26 },
        { limit: 221000000, rate: 0.27 },
        { limit: 390000000, rate: 0.28 },
        { limit: 463000000, rate: 0.29 },
        { limit: 561000000, rate: 0.30 },
        { limit: 709000000, rate: 0.31 },
        { limit: 965000000, rate: 0.32 },
        { limit: 1419000000, rate: 0.33 },
        { limit: Infinity, rate: 0.34 }
    ]
};


export const DTP_INCOME_LIMIT = 10000000;
export const NPWP_SURCHARGE_RATE = 1.20;

/**
 * Generates available tax years starting from 2025.
 * Automatically adds the next year if the current month is December (Real-time).
 * Always includes 2025 and 2026 as base.
 */
export const getAvailableTaxYears = (): number[] => {
    const now = new Date();
    const currentYear = now.getFullYear();
    const isDecember = now.getMonth() === 11; // 0-indexed, 11 is Dec
    
    // Base request: Start from 2025, 2026
    const minYear = 2025;
    let maxYear = 2026;

    // Auto-increment logic: 
    // If it's December 2026, we allow 2027.
    // If it's January 2027, we allow 2027.
    const realTimeNextYear = isDecember ? currentYear + 1 : currentYear;
    
    // Use the greater of the hardcoded max or the realtime max
    maxYear = Math.max(maxYear, realTimeNextYear);

    const years = [];
    for (let y = maxYear; y >= minYear; y--) {
        years.push(y);
    }
    // Include 2024 for backward compatibility if needed, but priority is 2025+
    years.push(2024);
    
    return years;
};

export const COUNTRIES = [
    { code: 'AFG', name: 'Afghanistan' },
    { code: 'AGO', name: 'Angola' },
    { code: 'ALB', name: 'Albania' },
    { code: 'AND', name: 'Andorra' },
    { code: 'ARE', name: 'United Arab Emirates' },
    { code: 'ARG', name: 'Argentina' },
    { code: 'ARM', name: 'Armenia' },
    { code: 'ATG', name: 'Antigua dan Barbuda' },
    { code: 'AUS', name: 'Australia' },
    { code: 'AUT', name: 'Austria' },
    { code: 'AZE', name: 'Azerbaijan' },
    { code: 'BDI', name: 'Burundi' },
    { code: 'BEL', name: 'Belgium' },
    { code: 'BEN', name: 'Benin' },
    { code: 'BFA', name: 'Burkina Faso' },
    { code: 'BGD', name: 'Bangladesh' },
    { code: 'BGR', name: 'Bulgaria' },
    { code: 'BHR', name: 'Bahrain' },
    { code: 'BHS', name: 'Bahamas' },
    { code: 'BIH', name: 'Bosnia dan Herzegovina' },
    { code: 'BLR', name: 'Belarus' },
    { code: 'BLZ', name: 'Belize' },
    { code: 'BOL', name: 'Bolivia' },
    { code: 'BRA', name: 'Brazil' },
    { code: 'BRB', name: 'Barbados' },
    { code: 'BRN', name: 'Brunei Darussalam' },
    { code: 'BTN', name: 'Bhutan' },
    { code: 'BWA', name: 'Bostwana' },
    { code: 'CAF', name: 'Central African Republic' },
    { code: 'CAN', name: 'Canada' },
    { code: 'CHE', name: 'Switzerland' },
    { code: 'CHL', name: 'Chile' },
    { code: 'CHN', name: 'China' },
    { code: 'CIV', name: 'Pantai Gading' },
    { code: 'CMR', name: 'Cameroon' },
    { code: 'COD', name: 'Congo - the Democratic Republic of the' },
    { code: 'COG', name: 'Congo' },
    { code: 'COL', name: 'Colombia' },
    { code: 'COM', name: 'Comoros' },
    { code: 'CPV', name: 'Cabo Verde' },
    { code: 'CRI', name: 'Costa Rica' },
    { code: 'CUB', name: 'Cuba' },
    { code: 'CYP', name: 'Cyprus' },
    { code: 'CZE', name: 'Republik Ceko' },
    { code: 'DEU', name: 'Germany' },
    { code: 'DJI', name: 'Djibouti' },
    { code: 'DMA', name: 'Dominica' },
    { code: 'DNK', name: 'Denmark' },
    { code: 'DOM', name: 'Dominican Republic' },
    { code: 'DSA', name: 'Aljazair' },
    { code: 'ECU', name: 'Ekuador' },
    { code: 'EGY', name: 'Egypt' },
    { code: 'ERI', name: 'Eritrea' },
    { code: 'ESP', name: 'Spain' },
    { code: 'EST', name: 'Estonia' },
    { code: 'ETH', name: 'Ethiopia' },
    { code: 'FIN', name: 'Finlandia' },
    { code: 'FJI', name: 'Fiji' },
    { code: 'FRA', name: 'France' },
    { code: 'FSM', name: 'Micronesia' },
    { code: 'GAB', name: 'Gabon' },
    { code: 'GBR', name: 'United Kingdom' },
    { code: 'GEO', name: 'Georgia' },
    { code: 'GHA', name: 'Ghana' },
    { code: 'GIN', name: 'Guinea' },
    { code: 'GMB', name: 'Gambia' },
    { code: 'GNB', name: 'Guinea-Bissau' },
    { code: 'GNQ', name: 'Equatorial Guinea' },
    { code: 'GRC', name: 'Greece' },
    { code: 'GRD', name: 'Grenada' },
    { code: 'GTM', name: 'Guatemala' },
    { code: 'GUY', name: 'Guyana' },
    { code: 'HKG', name: 'Hong Kong' },
    { code: 'HND', name: 'Honduras' },
    { code: 'HRV', name: 'Croatia' },
    { code: 'HTI', name: 'Haiti' },
    { code: 'HUN', name: 'Hungary' },
    { code: 'IND', name: 'India' },
    { code: 'IRL', name: 'Irlandia' },
    { code: 'IRN', name: 'Iran' },
    { code: 'IRQ', name: 'Iraq' },
    { code: 'ISL', name: 'Iceland' },
    { code: 'ISR', name: 'Israel' },
    { code: 'ITA', name: 'Italy' },
    { code: 'JAM', name: 'Jamaica' },
    { code: 'JOR', name: 'Jordan' },
    { code: 'JPN', name: 'Japan' },
    { code: 'KAZ', name: 'Kazakhstan' },
    { code: 'KEN', name: 'Kenya' },
    { code: 'KGZ', name: 'Kyrgyzstan' },
    { code: 'KHM', name: 'Cambodia' },
    { code: 'KIR', name: 'Kiribati' },
    { code: 'KNA', name: 'Saint Kitts dan Nevis' },
    { code: 'KOR', name: 'Korea, Republic of' },
    { code: 'KWT', name: 'Kuwait' },
    { code: 'LAO', name: 'Laos' },
    { code: 'LBN', name: 'Lebanon' },
    { code: 'LBR', name: 'Liberia' },
    { code: 'LBY', name: 'Libya' },
    { code: 'LCA', name: 'Saint Lucia' },
    { code: 'LIE', name: 'Liechtenstein' },
    { code: 'LKA', name: 'Sri Lanka' },
    { code: 'LSO', name: 'Lesotho' },
    { code: 'LTU', name: 'Lituania' },
    { code: 'LUX', name: 'Luxembourg' },
    { code: 'LVA', name: 'Latvia' },
    { code: 'MAR', name: 'Morocco' },
    { code: 'MCO', name: 'Monaco' },
    { code: 'MDA', name: 'Moldova, Republic of' },
    { code: 'MDG', name: 'Madagascar' },
    { code: 'MDV', name: 'Maldives' },
    { code: 'MEX', name: 'Mexico' },
    { code: 'MHL', name: 'Marshall Islands' },
    { code: 'MKD', name: 'Macedonia' },
    { code: 'MLI', name: 'Mali' },
    { code: 'MLT', name: 'Malta' },
    { code: 'MMR', name: 'Myanmar' },
    { code: 'MNE', name: 'Montenegro' },
    { code: 'MNG', name: 'Mongolia' },
    { code: 'MOZ', name: 'Mozambique' },
    { code: 'MRT', name: 'Mauritania' },
    { code: 'MUS', name: 'Mauritius' },
    { code: 'MWI', name: 'Malawi' },
    { code: 'MYS', name: 'Malaysia' },
    { code: 'NAM', name: 'Namibia' },
    { code: 'NER', name: 'Niger' },
    { code: 'NGA', name: 'Nigeria' },
    { code: 'NIC', name: 'Nicaragua' },
    { code: 'NLD', name: 'Netherlands' },
    { code: 'NOR', name: 'Norway' },
    { code: 'NPL', name: 'Nepal' },
    { code: 'NRU', name: 'Nauru' },
    { code: 'NZL', name: 'New Zealand' },
    { code: 'OMN', name: 'Oman' },
    { code: 'PAK', name: 'Pakistan' },
    { code: 'PAN', name: 'Panama' },
    { code: 'PER', name: 'Peru' },
    { code: 'PHL', name: 'Philippines' },
    { code: 'PLW', name: 'Palau' },
    { code: 'PNG', name: 'Papua New Guinea' },
    { code: 'POL', name: 'Poland' },
    { code: 'PRK', name: 'North Korea' },
    { code: 'PRT', name: 'Portugal' },
    { code: 'PRY', name: 'Paraguay' },
    { code: 'QAT', name: 'Qatar' },
    { code: 'ROU', name: 'Romania' },
    { code: 'RUS', name: 'Russian Federation' },
    { code: 'RWA', name: 'Rwanda' },
    { code: 'SAU', name: 'Saudi Arabia' },
    { code: 'SDN', name: 'Sudan' },
    { code: 'SEN', name: 'Senegal' },
    { code: 'SGP', name: 'Singapore' },
    { code: 'SLB', name: 'Solomon Islands' },
    { code: 'SLE', name: 'Sierra Leone' },
    { code: 'SLV', name: 'El Salvador' },
    { code: 'SMR', name: 'San Marino' },
    { code: 'SOM', name: 'Somalia' },
    { code: 'SRB', name: 'Serbia' },
    { code: 'STP', name: 'Sao Tome dan Principe' },
    { code: 'SUR', name: 'Suriname' },
    { code: 'SVK', name: 'Slovakia' },
    { code: 'SVN', name: 'Slovenia' },
    { code: 'SWE', name: 'Sweden' },
    { code: 'SWZ', name: 'Swaziland' },
    { code: 'SYC', name: 'Seychelles' },
    { code: 'SYR', name: 'Syria' },
    { code: 'TCD', name: 'Chad' },
    { code: 'TGO', name: 'Togo' },
    { code: 'THA', name: 'Thailand' },
    { code: 'TJK', name: 'Tajikistan' },
    { code: 'TKM', name: 'Turkmenistan' },
    { code: 'TLS', name: 'Timor Leste' },
    { code: 'TON', name: 'Tonga' },
    { code: 'TTO', name: 'Trinidad dan Tobago' },
    { code: 'TUN', name: 'Tunisia' },
    { code: 'TUR', name: 'Turkey' },
    { code: 'TUV', name: 'Tuvalu' },
    { code: 'TWN', name: 'Taiwan' },
    { code: 'TZA', name: 'Tanzania' },
    { code: 'UGA', name: 'Uganda' },
    { code: 'UKR', name: 'Ukraine' },
    { code: 'URY', name: 'Uruguay' },
    { code: 'USA', name: 'United States' },
    { code: 'UZB', name: 'Uzbekistan' },
    { code: 'VAT', name: 'Vatican' },
    { code: 'VCT', name: 'Saint Vincent dan Grenadines' },
    { code: 'VEN', name: 'Venezuela' },
    { code: 'VNM', name: 'Viet Nam' },
    { code: 'VUT', name: 'Vanuatu' },
    { code: 'WSM', name: 'Samoa' },
    { code: 'YEM', name: 'Yemen' },
    { code: 'ZAF', name: 'South Africa' },
    { code: 'ZMB', name: 'Zambia' },
    { code: 'ZWE', name: 'Zimbabwe' },
    { code: 'VGB', name: 'Virgin Islands, British' },
    { code: 'VIR', name: 'Virgin Islands, US' },
    { code: 'UMI', name: 'United States Minor Outlying Islands' },
    { code: 'TKL', name: 'Tokelau' },
    { code: 'SPM', name: 'Saint Pierre and Miquelon' },
    { code: 'SJM', name: 'Svalbard and Jan Mayen' },
    { code: 'SHN', name: 'Saint Helena, Ascension and Tristan da Cunha' },
    { code: 'SGS', name: 'South Georgia and the South Sandwich Islands' },
    { code: 'REU', name: 'Réunion' },
    { code: 'PYF', name: 'French Polynesia' },
    { code: 'PSE', name: 'Palestine, State of' },
    { code: 'ABW', name: 'Aruba' },
    { code: 'AIA', name: 'Anguilla' },
    { code: 'ALA', name: 'Aland Islands' },
    { code: 'ASM', name: 'American Samoa' },
    { code: 'ATA', name: 'Antarctica' },
    { code: 'ATF', name: 'French Southern Territories' },
    { code: 'BES', name: 'Bonaire, Sint Eustatius and Saba' },
    { code: 'BLM', name: 'Saint Barthélemy' },
    { code: 'BMU', name: 'Bermuda' },
    { code: 'BVT', name: 'Bouvet Island' },
    { code: 'CCK', name: 'Cocos (Keeling) Islands' },
    { code: 'COK', name: 'Cook Islands' },
    { code: 'CUW', name: 'Curacao' },
    { code: 'CXR', name: 'Christmas Island' },
    { code: 'CYM', name: 'Cayman Islands' },
    { code: 'DZA', name: 'Algeria' },
    { code: 'ESH', name: 'Western Sahara' },
    { code: 'FLK', name: 'Falkland Islands (Malvinas)' },
    { code: 'FRO', name: 'Faroe Islands' },
    { code: 'GGY', name: 'Guernsey' },
    { code: 'GIB', name: 'Gibraltar' },
    { code: 'GRL', name: 'Greenland' },
    { code: 'GUF', name: 'French Guiana' },
    { code: 'GUM', name: 'Guam' },
    { code: 'HMD', name: 'Heard Island and McDonald Islands' },
    { code: 'IMN', name: 'Isle of Man' },
    { code: 'IOT', name: 'British Indian Ocean Territory' },
    { code: 'JEY', name: 'Jersey' },
    { code: 'MAC', name: 'Macao' },
    { code: 'MAF', name: 'Saint Martin' },
    { code: 'MNP', name: 'Northern Mariana Islands' },
    { code: 'MSR', name: 'Montserrat' },
    { code: 'MTQ', name: 'Martinique' },
    { code: 'MYT', name: 'Mayotte' },
    { code: 'NCL', name: 'New Caledonia' },
    { code: 'NFK', name: 'Norfolk Island' },
    { code: 'NIU', name: 'Niue' },
    { code: 'PCN', name: 'Pitcairn' },
    { code: 'PRI', name: 'Puerto Rico' },
    { code: 'SSD', name: 'South Sudan' },
    { code: 'SXM', name: 'Sint Maarten (Dutch part)' },
    { code: 'TCA', name: 'Turks and Caicos Islands' },
    { code: 'WLF', name: 'Wallis and Futuna' },
];
